### PR TITLE
Updated Readme to reflect 2020.3 changes

### PR DESCRIPTION
**Pull request by dstreett**

### CODE REVIEW

**Comment by jbaldwin** [comment]
Is this good to merge or did you want to update the examples/readme.cpp file as well?

**Comment by dstreett** [comment]
I'm just a newb and forgot to push. Updated readme.cpp, should be good to merge.

**Comment by jbaldwin** [comment]
Haha, no prob!  Thanks for pushing this up.

**Comment by kevin-logan** [comment]
both readme examples from this PR are backwards, and if used as-is would result in a bad_optional_access

**Comment by jbaldwin** [comment]
whoops?

**Pull request merged**
